/*
(C) 2022-2025 Серый MLGamer. All freedoms preserved.
Дзен: <https://dzen.ru/seriy_mlgamer>
SoundCloud: <https://soundcloud.com/seriy_mlgamer>
YouTube: <https://www.youtube.com/@Seriy_MLGamer>
GitVerse: <https://gitverse.ru/Seriy_MLGamer>
E-mail: <Seriy-MLGamer@yandex.ru>

This file is part of Modularis Core.
Modularis Core is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Modularis Core is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Modularis Core. If not, see <https://www.gnu.org/licenses/>.
*/

#pragma once

#include <stdbool.h>
#include <Modularis_Core/system/types/Sound_value.h>
#include <stddef.h>

struct MDLRS_Safe_block;
struct MDLRS_Module;
struct MDLRS_Output;

struct MDLRS_Modularis
{
	unsigned sample_rate; /**Sample rate of a sound stream.*/
	bool lazy_update; /**Don't update disconnected modules.*/
	bool dispose_leaks; /**Dispose "safe memory" blocks if they are not disposed during cleanup due to memory leaks.*/
	struct MDLRS_Safe_block *last_block; /**A last block of "safe memory" system block list.*/
	size_t block_count, max_block_count, allocated, max_allocated; /**"Safe memory" system memory account.*/
	struct MDLRS_Module **disconnected_modules; /**Modules that aren't connected to any module.*/
	unsigned disconnected_module_count; /**Element count in an array.*/
	unsigned note_scancode;
	struct MDLRS_Output *output; /**Module for returning new frames of a sound stream.*/
};
/**
 * Create an instance of Modularis program generating a sound stream.
 * @param sample_rate the sample rate of a sound stream.
 * @param channels the number of channels in a stream.
 * @returns an instance of Modularis in the heap.
 */
struct MDLRS_Modularis *MDLRS_Modularis_new(unsigned sample_rate, unsigned channels);
/**
 * Initialize an instance of Modularis program generating a sound stream.
 * @param self
 * @param sample_rate the sample rate of a sound stream.
 * @param channels the number of channels in a stream.
 */
void MDLRS_Modularis_init(struct MDLRS_Modularis *self, unsigned sample_rate, unsigned channels);
/**
 * Update all modules in the Modularis project. If lazy_update field is true, then disconnected modules are excluded.
 * @param self
 */
void MDLRS_Modularis_update(struct MDLRS_Modularis *self);
/**
 * Get a value of sound frame generated by the update() method at the specified channel.
 * @param self
 * @param channel
 * @return a value of sound frame.
 */
MDLRS_Sound_value MDLRS_Modularis_get(struct MDLRS_Modularis *self, unsigned channel);
void MDLRS_Modularis_deinit(struct MDLRS_Modularis *self);
void MDLRS_Modularis_remove(struct MDLRS_Modularis *self);