/*
(C) 2022-2025 Серый MLGamer. All freedoms preserved.
Дзен: <https://dzen.ru/seriy_mlgamer>
SoundCloud: <https://soundcloud.com/seriy_mlgamer>
YouTube: <https://www.youtube.com/@Seriy_MLGamer>
GitVerse: <https://gitverse.ru/Seriy_MLGamer>
E-mail: <Seriy-MLGamer@yandex.ru>

This file is part of Modularis Core C++.
Modularis Core C++ is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Modularis Core C++ is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Modularis Core C++. If not, see <https://www.gnu.org/licenses/>.
*/

#pragma once

#include <Modularis_Core_C++/system/types/Sound_value.hpp>
#include <cstddef>

namespace MDLRS
{
	struct Safe_block;
	struct Module;
	struct Output;

	struct Modularis
	{
		unsigned sample_rate; /**Sample rate of a sound stream.*/
		bool lazy_update; /**Don't update disconnected modules.*/
		bool dispose_leaks; /**Dispose "safe memory" blocks if they are not disposed during cleanup due to memory leaks.*/
		Safe_block *last_block; /**A last block of "safe memory" system block list.*/
		size_t block_count, max_block_count, allocated, max_allocated; /**"Safe memory" system memory account.*/
		Module **disconnected_modules; /**Modules that aren't connected to any module.*/
		unsigned disconnected_modules_count; /**Element count in an array.*/
		unsigned note_scancode;
		Output *output; /**Module for returning new frames of a sound stream.*/

		/**
		 * Create an instance of Modularis program generating a sound stream.
		 * @param sample_rate the sample rate of a sound stream.
		 * @param channels the number of channels in a stream.
		 * @returns an instance of Modularis in the heap.
		 */
		void *operator new(size_t size);
		void *operator new[](size_t size)=delete;
		/**
		 * Initialize an instance of Modularis program generating a sound stream.
		 * @param sample_rate the sample rate of a sound stream.
		 * @param channels the number of channels in a stream.
		 */
		Modularis(unsigned sample_rate, unsigned channels);
		/**
		 * Update all modules in the Modularis project. If lazy_update field is true, then disconnected modules are excluded.
		 */
		void update();
		/**
		 * Get a value of sound frame generated by the update() method at the specified channel.
		 * @param channel
		 * @return a value of sound frame.
		 */
		Sound_value get(unsigned channel);
		~Modularis();
		void operator delete(void *data);
		void operator delete[](void *data)=delete;
	};
}